BRAND_DICT = \
    [
        'alcatel',
        'ami',
        'apple',
        'benco',
        'el',
        'energizer',
        'evertek',
        'honor',
        'huawei',
        'iku',
        'infinix',
        'iplus',
        'ipro',
        'itel',
        'kxd',
        'lenovo',
        'logicom',
        'nokia',
        'oneplus',
        'oppo',
        'oukitel',
        'realme',
        'samsung',
        'schneider',
        'smart',
        'tcl',
        'tecno',
        'umidigi',
        'vivo',
        'xiaomi',
        'zte',
        'brondi',
        'doogee',
        'asus',
        'lpro',
        'figi'
    ]

Colors = {
    'ambre jaune': 'amber yellow',
    'aqua verte': 'aqua green',
    'atlantique bleu': 'atlantic blue',
    'beige': 'beige',
    'bleu': 'blue',
    'bleu titan': 'blue titanium',
    'bleu turquoise': 'turquoise blue',
    'blanc': 'white',
    'noir': 'black',
    'blanc & bleu': 'black & blue',
    'blanc & vert': 'black & green',
    'blanc & rouge': 'black & red',
    'blanc noir': 'midnight black',
    'blanc vert': 'black green',
    'blanc orange': 'black orange',
    'blanc et bleu': 'black&blue',
    'blanc et rouge': 'black&red',
    'blanc et argent': 'black&silver',
    'silver': 'silver',
    'bleu': 'blue',
    'bleu titan': 'blue titanium',
    'titane': 'titanium',
    'brun': 'brown',
    'carbone noir': 'carbon black',
    'cuivre': 'copper',
    'crème': 'cream',
    'cyane': 'cyan',
    'cyane bleu': 'cyan blue',
    'vert foncé': 'dark blue',
    'diamant argent': 'diamond silver',
    'forêt noir': 'forest black',
    'forêt vert': 'forest green',
    'givre bleu': 'frost blue',
    'or': 'gold',
    'granit bleu': 'granite blue',
    'granit gris': 'granite gray',
    'graphe': 'graphite',
    'gris graphite': 'graphite gray',
    'vert': 'green',
    'gris': 'grey',
    'vert clair': 'light green',
    'vert lime': 'lime green',
    'magie bleue': 'magic blue',
    'peau magique': 'magic skin',
    'marigold': 'marigold',
    'mauve': 'mauve',
    'midnight': 'midnight',
    'vert minuit': 'midnight black',
    'vert menthe': 'mint green',
    'minuit': 'minuit',
    'bleu lune': 'moon blue',
    'titanium naturel': 'natural titanium',
    'nobel noir': 'noble black',
    'océan bleu': 'ocean blue',
    'onyx noir': 'onyx black',
    'onyx gris': 'onyx gray',
    'orange': 'orange',
    'pierre pebble': 'pebble white',
    'pourpre': 'purple',
    'rouge': 'red',
    'rose': 'rose',
    'rose d\'or': 'rose gold',
    'mer bleue': 'sea blue',
    'argent': 'silver',
    'blue': 'blue',
    'graphite': 'graphite',
    'ciel bleu': 'sky blue',
    'étoile': 'starlight',
    'or du lever': 'sunrise gold',
    'or du coucher': 'sunset gold',
    'averse de soleil': 'sunshower',
    'titanium': 'titanium',
    'titanium noir': 'titanium black',
    'titanium jaune': 'titanium yellow',
    'turquoise': 'turquoise',
    'bleu turquoise': 'turquoise blue',
    'crepuscule bleu': 'twilight blue',
    'violet': 'violet',
    'jaune': 'yellow'
}
